### ISSUE TITLE
About “seed” issues

### ISSUE THREAD

**Issue by konioyxgq** [HuangYG123/CurricularFace#13]
Putting **seed** in the **main** function seems useless, so that each training is different and cannot reproduce the results. Does it put **seed** in the **main_worker** function?

**Comment by HuangYG123** [comment]
Thanks for pointing out this. The seed should be put in each process init function. In our environment,  the training process is started with a script, so there is no such problem. We will fix it.

**Comment by konioyxgq** [comment]
Thank you for your reply. I don't understand two things.
1、Do you mean "each process init function" by the "main_worker" function? If not, what is it?
2、In "the process is started with a script", does "script" refer to the "train.sh" file? I see that there is nothing special about the train.sh file. Why is there no such problem?

**Comment by HuangYG123** [comment]
1. Yes. In this code, the init function is the "main_worker" function.
2. Sorry for not expressing clearly. The script does not refer to the 'train.sh.' I mean, in our training platform，we have another script to start the training. In this version of the code, the init should be added into the "main_worker" function.

**Comment by konioyxgq** [comment]
Thank you very much for your reply.
Can you disclose your other training scripts? I think I should be able to learn some training skills, thank you very much.

**Comment by HuangYG123** [comment]
There are no special operations in it, just some environment initialization steps. But it is a part of an internal tool, and I am sorry that it cannot be made public for the time being.

**Comment by konioyxgq** [comment]
Okay, I got it. Thank you for your reply.
