### ISSUE TITLE
Run Time Error

### ISSUE THREAD

**Issue by weiyichang** [HuangYG123/CurricularFace#2]
Hi,

Thanks for sharing this code.

I have tried to train this repo with my data, but I got this error:

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation (both ArcFace and CurricularFace)
Any suggestions?

BTW, the version of tqdm in requirements.txt seems wrong (no 4.31.2)

maybe:
 4.31.1, 4.32.0, 4.32.1, 4.32.2

Thanks!!!

**Comment by HuangYG123** [comment]
Thanks for pointing our the tqdm version error. It should be 4.32.2. I guess maybe the code cos_theta.scatter_(1, label.view(-1, 1).long(), final_target_logit) leads to the error.  You can change this line to non_inplace op.
I only tested the code on Pytorch 1.1.0.

**Comment by weiyichang** [comment]
Hi,

Thanks for your quick response

I will try it !

Thanks!!!

**Comment by weiyichang** [comment]
============Update======
Seems due to this line

`cos_theta[mask] = hard_example * (self.t + hard_example)`

I replace this line with:
`hard_value = cos_theta * (self.t + cos_theta)`
`cos_theta_out = torch.where(mask==1,hard_value,cos_theta)`

It could run, but I am not sure that the result is the same as the original one ? 

(Could you help me to verify it ? )

Thanks !!!

**Comment by HuangYG123** [comment]
The result seems to be the same. The loss value at the first step is about 42.

**Comment by weiyichang** [comment]
Hi,

Got it, and thank you for your kind assistance :)
