### ISSUE TITLE
Error in train.py about builtins.print

### ISSUE THREAD

**Issue by bigAndSmall** [HuangYG123/CurricularFace#27]
Hello, i meet an error on train.py on line 51
and the error message is: builtins.print = print_pass SyntaxError: invalid syntax. Can someone help me with this problem? Thanks a lot!

**Comment by wangs311** [comment]
hi, I have met the same error. How do you solve it? Thanks a lot!

**Comment by bigAndSmall** [comment]
just install builtins



---Original---

**Comment by wangs311** [comment]
Thank you! The problem was solved by your solution!
