### ISSUE TITLE
IR101 acc

### ISSUE THREAD

**Issue by xisi789** [HuangYG123/CurricularFace#3]
Hi,

Thanks for sharing this code.

I have tried to test IR101 pretrained model with evaluate.sh, but I got this result:

============================================================
Evaluation: LFW Acc: 0.6561666666666667, CFP_FP Acc: 0.6135714285714285, AgeDB Acc: 0.5056666666666667, CPLFW Acc: 0.5356666666666666 CALFW Acc: 0.5483333333333333

what's wrong?

Thanks!!!

**Comment by HuangYG123** [comment]
I have add the results of the pretrained model on each dataset.  Seems the pretrained weights are not correctly loaded.

**Comment by KamalM8** [comment]
@xisi789 were you able to fix these issues? I have the same issues with these datasets and IJB-C.

**Comment by xisi789** [comment]
> @xisi789 were you able to fix these issues? I have the same issues with these datasets and IJB-C.


Yes, I solved the problem，But time has passed so long. I’m not sure how it was solved at the time. It seems to be data preprocessing.

**Comment by luhairong11** [comment]
> Hi,
> 
> Thanks for sharing this code.
> 
> I have tried to test IR101 pretrained model with evaluate.sh, but I got this result:
> 
> ============================================================
> Evaluation: LFW Acc: 0.6561666666666667, CFP_FP Acc: 0.6135714285714285, AgeDB Acc: 0.5056666666666667, CPLFW Acc: 0.5356666666666666 CALFW Acc: 0.5483333333333333
> 
> what's wrong?
> 
> Thanks!!!

I have the same problem, Are you solve?
