### ISSUE TITLE
I would like to ask how the original training picture size is 250x250, when training, it becomes 112x112?

### ISSUE THREAD

**Issue by 18082170505** [HuangYG123/CurricularFace#30]

**Comment by HuangYG123** [comment]
The original images should first be cropped with five landmarks provided by some face detection models.

**Comment by 18082170505** [comment]
I have solved this problem by MTCNN.Thank you for your reply.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月23日(星期三) 下午3:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HuangYG123/CurricularFace] I would like to ask how the original training picture size is 250x250, when training, it becomes 112x112? (#30)





 
The original images should first be cropped with five landmarks provided by some face detection models.
