### ISSUE TITLE
训练速度慢

### ISSUE THREAD

**Issue by ruiming46zrm** [HuangYG123/CurricularFace#4]
谢谢作者的分享。ir101模型我在私有集上测过了（现实监控场景多角度）， 效果很棒， 89%，  arcface作者模型只有83%。 

But在训自己的数据集， 4卡速度十分慢，是arcface的2.5倍，，，

**Comment by zhaoym55** [comment]
我训练自己的数据集也收敛很慢，而且越往后训练出现低far其tar值下降的问题

**Comment by HuangYG123** [comment]
@ruiming46zrm  Thanks for the response to the result.   As reported in the paper, the training speed may be slightly lower than ArcFace, not so slow. Please check the GPU setting.

**Comment by ruiming46zrm** [comment]
@HuangYG123  thanks for reply.  1st epoch 13h,  now training 2nd epoch need 6h , it turns back....

**Comment by 1icas** [comment]
@ruiming46zrm  hi，您好，请问可以留一个邮箱吗，想问一个问题。有偿～

**Comment by llf1234** [comment]
@ruiming46zrm 之前我也遇到过类似的情况，虽然用vgg2训练在其他私有测试集合上又提升，但是用私有训练集合训练，就不是这回事了，你试过在私有训练数据集合上用arcface和curriculumface训练做对比，然后在私有测试集合上测试吗？

**Comment by ruiming46zrm** [comment]
> @ruiming46zrm hi，您好，请问可以留一个邮箱吗，想问一个问题。有偿～

微信ruiming46zrm

**Comment by ruiming46zrm** [comment]
> @ruiming46zrm 之前我也遇到过类似的情况，虽然用vgg2训练在其他私有测试集合上又提升，但是用私有训练集合训练，就不是这回事了，你试过在私有训练数据集合上用arcface和curriculumface训练做对比，然后在私有测试集合上测试吗？

我没有专门的私有训练集，私有集都是和共有集一起清洗合并了的。你在私有集上训练效果差很多么？ 可能要关注你私有集的干净成都，因为curricular后期关注难样本，如果关注成了脏样本，那么. . .
