### ISSUE TITLE
target_logit's shape

### ISSUE THREAD

**Issue by xingronaldo** [HuangYG123/CurricularFace#42]
target_logit = cos_theta[torch.arange(0, embbedings.size(0)), label].view(-1, 1)

By this line, it seems the shape is [embbedings.size(0) * embbedings.size(0), 1]. Is it true?

**Comment by xingronaldo** [comment]
Solved. The label shape should be of 1-dim, i.e. [B] rather than [B, 1]. But when it is [B, 1], the output will be of [B*B, 1].

**Comment by Glisten-5481** [comment]
Sorry to bother you, but could you please tell me how to specifically modify this problem in the code?
