### ISSUE TITLE
How to preprae the data record dir?

### ISSUE THREAD

**Issue by diggerdu** [HuangYG123/CurricularFace#7]
Thanks for your generous sharing. But the readme don't mention how to generate the `RECORD_DIR`.

**Comment by HuangYG123** [comment]
We use the refined ms1mv2 provided by the authors of arcface. We transform the released train.rec and train.idx to the original images.

**Comment by diggerdu** [comment]
Thanks for your reply.

**Comment by XGuider** [comment]
@diggerdu @HuangYG123 HI,are you find refined_ms1m.txt? I fellow " transform the released train.rec and train.idx to the original images."，but not this file.how to get this file?thnx your help!
