### ISSUE TITLE
some different between implementation and paper

### ISSUE THREAD

**Issue by superhero1991** [HuangYG123/CurricularFace#8]
Hi, 
    When you update the t. you use 0.99 as the alpha in the paper. but only 0.01 in the code. So, which one is the right version. In my opinion, the code is right.

**Comment by HuangYG123** [comment]
Sorry for the mistake. The code is the right version

**Comment by superhero1991** [comment]
> Sorry for the mistake. The code is the right version

One more question. when I try to train a new model(use resnet18 as the backbone). I found the t value is 0.4 in first stage(it's 0.6 in your paper). I don't know why there has a gap. It's depends on the backbone? Thank you very much

**Comment by HuangYG123** [comment]
@superhero1991  Since the value of t is based on the positive similarities，small backbone may be harder to increase the positive similarites.

**Comment by superhero1991** [comment]
> @superhero1991 Since the value of t is based on the positive similarities，small backbone may be harder to increase the positive similarites.

@HuangYG123 thank you very much. Is it possible to add a small value on t? Maybe it hard to convergence.
